import type { Metadata } from 'next'
import localFont from 'next/font/local'

import './globals.css'
import PageContainer from './components/PageContainer'


const satoshi = localFont({
    src: [
        {
            path: '../public/fonts/Satoshi-Regular.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../public/fonts/Satoshi-Italic.woff2',
            weight: '400',
            style: 'italic',
        },
        {
            path: '../public/fonts/Satoshi-Bold.woff2',
            weight: '900',
            style: 'bold',
        },
    ],
})


export const metadata: Metadata = {
    title: 'Armst209.dev',
    description:
        'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html
            lang='en'
            className={`${satoshi.className} h-full antialiased`}
        >
            <body className='min-h-full flex flex-col'>
                <PageContainer>
                    {children}
                </PageContainer>

            </body>
        </html>
    )
}
